apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: podcloud-data
  namespace: podcloud
spec:
  accessModes: ["ReadWriteOnce"]
  storageClassName: standard
  resources:
    requests:
      storage: 1Gi
